
https://ezplatformcloud.contextualcode.site/:
    type: upstream
    upstream: app:http
    cache:
        enabled: false

https://ezplatformcloud.ccplatform.net/:
    type: upstream
    upstream: app:http
    cache:
        enabled: false
